/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Beans.Detalle_servicio;
import Beans.Reservacion;
import Beans.Servicio_habitacion;
import Controlador.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.table.DefaultTableModel;


public class Vista_servicio extends javax.swing.JFrame {
    Controlador_detalleservicio detalle = new Controlador_detalleservicio();
    controlador_servicio servicio = new controlador_servicio();
    controlador_reservacion Reservaciones =new controlador_reservacion();
    DefaultTableModel dt = new DefaultTableModel();
    Servicio_habitacion v=new Servicio_habitacion();
   
    double tpagar;
    int cant;
    double preci;
    int idp;
    double total = 0;
    int iddetalle=0;
    
    
    public Vista_servicio() {
        initComponents();
        generarnropedido();
        muestra2(Integer.parseInt(jtxtcodigosh.getText()));
        jtxtfecha_hora.setText(fechahora());
        jtxtmonto.setEditable(false);
        jtxtPresio.setEditable(false);
        jtxtidproducto.setEditable(false);
        jtxtnombreproduc.setEditable(false);
        this.setLocationRelativeTo(null);
    }
        //GENERAR NUEMRO DE PEDIDO
    void generarnropedido() {
        String nropedido = servicio.nroPedido();
        if (nropedido == null) {
            jtxtcodigosh.setText("000001");
        } else {
            int increment = Integer.parseInt(nropedido);
            increment = increment + 1;
            jtxtcodigosh.setText("00000" + increment);
        }
    }
 
    public String  fechahora(){
        LocalDate fechaactual = LocalDate.now();
        return (fechaactual+"");
    }
    
    public void limpiarTabla(){
        try {
        DefaultTableModel modelo=(DefaultTableModel) tabledetalle.getModel();
        int filas=tabledetalle.getRowCount();
        for (int i = 0;i<=filas; i++) {
        modelo.removeRow(0);
        }
        } catch (Exception e) {
        
        }
        }  
 
    
    void muestra2(Integer cod){
      tpagar=0;
      dt=(DefaultTableModel)tabledetalle.getModel();
      dt.setRowCount(0);
//       tpagar = 0;
      for(Detalle_servicio x:detalle.ListadoDet(cod)){
          Object v[]={x.getId_detalle(),x.getCodigo_sh(),x.getId_produto(),x.getNombre_producto(),x.getPreciopro(),x.getCantidad(),x.getTotal()};
          tpagar = tpagar + x.getTotal();
          jtxttotal.setText("" + tpagar + "0");
          dt.addRow(v);
         
      }
  }
    
    public void CargarDatosProducto(){
        
        buscarproducto ventana2 = new buscarproducto();
        int producto = ventana2.idpro;
        String NomProducto = ventana2.nompro;
        
        this.jtxtidproducto.setText(String.valueOf(producto));
        this.jtxtnombreproduc.setText(NomProducto);
    }
    
   void ListaServicios(){
      dt=(DefaultTableModel)jTablaListadoReserva.getModel();
      dt.setRowCount(0);
       //tpagar = 0;
      for(Servicio_habitacion x:servicio.Listado()){
          Object v[]={x.getCodigo_sh(),x.getCodigo_reservacion(),x.getDni_cliente(),x.getNombre_cliente(),x.getHabitacion(),x.getFecha_hora()};
          dt.addRow(v);
         
      }
  }  
   void muestra3(String cod){
        try {
      dt=(DefaultTableModel)jTablaListadoReserva.getModel();
      dt.setRowCount(0);
      for(Servicio_habitacion x:servicio.BusquedaNombre(cod)){
          Object v[]={x.getCodigo_sh(),x.getCodigo_reservacion(),x.getDni_cliente(),x.getNombre_cliente(),x.getHabitacion(),x.getFecha_hora()};
        dt.addRow(v);
      }
        } catch (Exception e) {
        }
  } 
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtnombrecliente = new javax.swing.JTextField();
        jtxtfecha_hora = new javax.swing.JTextField();
        jtxtcodigoreser = new javax.swing.JTextField();
        jtxtcodigosh = new javax.swing.JTextField();
        jtxtdnicliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtidproducto = new javax.swing.JTextField();
        jtxtnombreproduc = new javax.swing.JTextField();
        jtxtcantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledetalle = new javax.swing.JTable();
        btnagregarrpro = new javax.swing.JButton();
        btnserviciogenerar = new javax.swing.JButton();
        btnmostrarproductos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxttotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtPresio = new javax.swing.JTextField();
        jtxtmonto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btneliminarrpro = new javax.swing.JButton();
        btnactualizarpro = new javax.swing.JButton();
        jtxtactualizarservicio = new javax.swing.JButton();
        jtxteliminarservicio = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtxthabitacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaListadoReserva = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtbuscarxnombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SERVICIO A LA HABITACION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("CODIGO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setText("CODIGO DE RESERVACION");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setText("DNI");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jLabel5.setText("NOMBRE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jLabel6.setText("FECHA ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jtxtnombrecliente.setEnabled(false);
        jPanel2.add(jtxtnombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 180, -1));

        jtxtfecha_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfecha_horaActionPerformed(evt);
            }
        });
        jtxtfecha_hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtfecha_horaKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtfecha_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 180, -1));

        jtxtcodigoreser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoreserActionPerformed(evt);
            }
        });
        jtxtcodigoreser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcodigoreserKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtcodigoreser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, -1));

        jtxtcodigosh.setEnabled(false);
        jtxtcodigosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcodigoshActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtcodigosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 180, -1));

        jtxtdnicliente.setEnabled(false);
        jPanel2.add(jtxtdnicliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 180, -1));

        jLabel7.setText("ID DEL PRODUCTO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel8.setText("NOMBRE DEL PRODUCTO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 130, -1));

        jtxtidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtidproductoActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtidproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 140, -1));

        jtxtnombreproduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnombreproducActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtnombreproduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 180, -1));

        jtxtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcantidadActionPerformed(evt);
            }
        });
        jtxtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcantidadKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 90, -1));

        tabledetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID DETALLE", "CODIGO SH", "ID PRODUCTO", "NOMBRE PRODUCTO", "PRECIO", "CANTIDAD", "TOTAL "
            }
        ));
        tabledetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledetalle);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 870, 290));

        btnagregarrpro.setText("AGREGAR PRODUCTOS");
        btnagregarrpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarrproActionPerformed(evt);
            }
        });
        jPanel2.add(btnagregarrpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 180, -1));

        btnserviciogenerar.setText("GENERAR SERVICIO");
        btnserviciogenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserviciogenerarActionPerformed(evt);
            }
        });
        jPanel2.add(btnserviciogenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 700, -1, -1));

        btnmostrarproductos.setText("MOSTRAR PRODUCTOS");
        btnmostrarproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarproductosActionPerformed(evt);
            }
        });
        jPanel2.add(btnmostrarproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 180, -1));

        jLabel1.setText("TOTAL A PAGAR :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, -1, -1));

        jtxttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttotalActionPerformed(evt);
            }
        });
        jPanel2.add(jtxttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 170, 30));

        jLabel10.setText("PRECIO");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel11.setText("CANTIDAD");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 10));
        jPanel2.add(jtxtPresio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 90, -1));
        jPanel2.add(jtxtmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 160, -1));

        jLabel9.setText("MONTO");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        btneliminarrpro.setText("ELIMINAR PRODUCTOS");
        btneliminarrpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarrproActionPerformed(evt);
            }
        });
        jPanel2.add(btneliminarrpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 180, 30));

        btnactualizarpro.setText("ACTUALIZAR PRODUCTOS");
        btnactualizarpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarproActionPerformed(evt);
            }
        });
        jPanel2.add(btnactualizarpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 180, -1));

        jtxtactualizarservicio.setText("ACTUALIZAR SERVICIO");
        jtxtactualizarservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtactualizarservicioActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtactualizarservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 700, -1, -1));

        jtxteliminarservicio.setText("ELIMINAR SERVICIO");
        jtxteliminarservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxteliminarservicioActionPerformed(evt);
            }
        });
        jPanel2.add(jtxteliminarservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, -1, -1));

        jLabel12.setText("HABITACION");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));
        jPanel2.add(jtxthabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 180, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 930, 730));

        jTabbedPane1.addTab("SERVICIO HABITACION", jPanel2);

        jTablaListadoReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "COD. SERVICIO", "COD. RESERVACION", "DNI", "NOMBRE CLIENTE", "HABITACION", "FECHA HORA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaListadoReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaListadoReservaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablaListadoReserva);

        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtbuscarxnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarxnombreActionPerformed(evt);
            }
        });
        txtbuscarxnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarxnombreKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtbuscarxnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtbuscarxnombre))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HISTORIAL DE SERVICIOS", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtidproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtidproductoActionPerformed

    private void btnagregarrproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarrproActionPerformed
        
        Detalle_servicio ep=new Detalle_servicio();
        ep.setCodigo_sh(Integer.parseInt(jtxtcodigosh.getText()));
        ep.setId_produto(Integer.parseInt(jtxtidproducto.getText()));
        ep.setNombre_producto(jtxtnombreproduc.getText());
        ep.setPreciopro(Double.parseDouble(jtxtPresio.getText()));
        ep.setCantidad(Integer.parseInt(jtxtcantidad.getText()));
        ep.setTotal(Double.parseDouble(jtxtmonto.getText()));    
       detalle.insertar(ep);//GRABA TABLA
       muestra2(Integer.parseInt(jtxtcodigosh.getText()));
    }//GEN-LAST:event_btnagregarrproActionPerformed

    private void jtxtcodigoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoshActionPerformed

    private void btnserviciogenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserviciogenerarActionPerformed
        Servicio_habitacion ep=new Servicio_habitacion();
        ep.setCodigo_sh(Integer.parseInt(jtxtcodigosh.getText()));
        ep.setCodigo_reservacion(Integer.parseInt(jtxtcodigoreser.getText()));
        ep.setDni_cliente(Integer.parseInt(jtxtdnicliente.getText()));
        ep.setFecha_hora(jtxtfecha_hora.getText());
        ep.setNombre_cliente(jtxtnombrecliente.getText());
        ep.setHabitacion(jtxthabitacion.getText());
        ep.setTotal(Double.parseDouble(jtxttotal.getText()));
        servicio.insertar(ep);//GRABA TABLA
        generarnropedido();
        limpiacajastodo();
        limpiarTabla();
    }//GEN-LAST:event_btnserviciogenerarActionPerformed

    private void btnmostrarproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarproductosActionPerformed
        buscarproducto p = new buscarproducto();
        p.setVisible(true);
       
        
        buscarproducto ventana2 = new buscarproducto();
        jtxtidproducto.setText("" + ventana2.idpro);
        jtxtnombreproduc.setText(ventana2.nompro);
        jtxtPresio.setText(ventana2.preciopro);
    }//GEN-LAST:event_btnmostrarproductosActionPerformed

    private void jtxttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxttotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ListaServicios();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablaListadoReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaListadoReservaMouseClicked
        
        int filaselec =  jTablaListadoReserva.rowAtPoint(evt.getPoint());
        jtxtcodigosh.setText(jTablaListadoReserva.getValueAt(filaselec, 0).toString());
        jtxtcodigoreser.setText(jTablaListadoReserva.getValueAt(filaselec, 1).toString());
        jtxtdnicliente.setText(jTablaListadoReserva.getValueAt(filaselec, 2).toString());
        jtxtnombrecliente.setText(jTablaListadoReserva.getValueAt(filaselec, 3).toString());
        jtxthabitacion.setText(jTablaListadoReserva.getValueAt(filaselec, 4).toString());
        jtxtfecha_hora.setText(jTablaListadoReserva.getValueAt(filaselec, 5).toString());
        int CodServicioHabitacion=Integer.parseInt(jTablaListadoReserva.getValueAt(filaselec, 0).toString());      
        muestra2(CodServicioHabitacion);
        
        
        
    }//GEN-LAST:event_jTablaListadoReservaMouseClicked

    private void jtxtcodigoreserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcodigoreserKeyReleased
        // TODO add your handling code here:
        try {
        for(Reservacion x: Reservaciones.BusquedaReservacion(jtxtcodigoreser.getText())){  
            jtxtdnicliente.setText(String.valueOf(x.getId_cliente()));
            jtxtnombrecliente.setText(String.valueOf(x.getId_empleado()));
        }
            
        } catch (Exception e) {
        }  
        
        
    }//GEN-LAST:event_jtxtcodigoreserKeyReleased

    private void jtxtnombreproducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnombreproducActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnombreproducActionPerformed

    private void jtxtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcantidadActionPerformed

    private void jtxtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcantidadKeyReleased
        try {
        double pre = Double.parseDouble(jtxtPresio.getText()); 
        int can = Integer.parseInt(jtxtcantidad.getText()); 
        double pretotal = pre*can;
        jtxtmonto.setText(String.valueOf(pretotal));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtxtcantidadKeyReleased

    private void tabledetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledetalleMouseClicked
        int f=tabledetalle.getSelectedRow();
        iddetalle=Integer.parseInt(tabledetalle.getValueAt(f,0).toString());
        jtxtcodigosh.setText(tabledetalle.getValueAt(f,1).toString());
        jtxtidproducto.setText(tabledetalle.getValueAt(f,2).toString());
        jtxtnombreproduc.setText(tabledetalle.getValueAt(f,3).toString());
        jtxtPresio.setText(tabledetalle.getValueAt(f,4).toString());
        jtxtcantidad.setText(tabledetalle.getValueAt(f,5).toString());
        jtxtmonto.setText(tabledetalle.getValueAt(f,6).toString());
        //desactivar 
        btnagregarrpro.setEnabled(false);
        
    }//GEN-LAST:event_tabledetalleMouseClicked

    private void btneliminarrproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarrproActionPerformed
        Detalle_servicio ds=new Detalle_servicio();
        detalle.eliminar(iddetalle);  
        muestra2(Integer.parseInt(jtxtcodigosh.getText()));
        limpiacajasproductos();
    }//GEN-LAST:event_btneliminarrproActionPerformed

    private void btnactualizarproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarproActionPerformed

        Detalle_servicio ds=new Detalle_servicio();
        ds.setId_detalle(iddetalle);
        ds.setCodigo_sh(Integer.parseInt(jtxtcodigosh.getText()));
        ds.setId_produto(Integer.parseInt(jtxtidproducto.getText()));
        ds.setNombre_producto(jtxtnombreproduc.getText());
        ds.setPreciopro(Double.parseDouble(jtxtPresio.getText()));
        ds.setCantidad(Integer.parseInt(jtxtcantidad.getText()));
        ds.setTotal(Double.parseDouble(jtxtmonto.getText()));
        detalle.actualizar(ds);  
        muestra2(Integer.parseInt(jtxtcodigosh.getText()));
        limpiacajasproductos();
    }//GEN-LAST:event_btnactualizarproActionPerformed

    private void jtxtfecha_horaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfecha_horaKeyTyped

    }//GEN-LAST:event_jtxtfecha_horaKeyTyped

    private void jtxtactualizarservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtactualizarservicioActionPerformed
        Servicio_habitacion s = new Servicio_habitacion();
        s.setCodigo_reservacion(Integer.parseInt(jtxtcodigoreser.getText()));
        s.setCodigo_sh(Integer.parseInt(jtxtcodigosh.getText()));
        s.setDni_cliente(Integer.parseInt(jtxtdnicliente.getText()));
        s.setFecha_hora(jtxtfecha_hora.getText());
        s.setNombre_cliente(jtxtnombrecliente.getText());
        s.setHabitacion(jtxthabitacion.getText());
        s.setTotal(Double.parseDouble(jtxttotal.getText()));
        servicio.actualizar(s);
        limpiacajasservicio();
        limpiarTabla();
    }//GEN-LAST:event_jtxtactualizarservicioActionPerformed

    private void jtxteliminarservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxteliminarservicioActionPerformed
        Servicio_habitacion s = new Servicio_habitacion();
        detalle.eliminarsh(Integer.parseInt(jtxtcodigosh.getText()));
        servicio.eliminar(Integer.parseInt(jtxtcodigosh.getText()));
        limpiacajastodo();
        limpiarTabla();

    }//GEN-LAST:event_jtxteliminarservicioActionPerformed

    private void jtxtfecha_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfecha_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfecha_horaActionPerformed

    private void txtbuscarxnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarxnombreActionPerformed
    
    }//GEN-LAST:event_txtbuscarxnombreActionPerformed

    private void txtbuscarxnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarxnombreKeyReleased
        try {
                  muestra3(txtbuscarxnombre.getText());  
        } catch (Exception e) {
        }
    
    }//GEN-LAST:event_txtbuscarxnombreKeyReleased

    private void jtxtcodigoreserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcodigoreserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcodigoreserActionPerformed
    
    void limpiacajasservicio() {
        jtxtcodigoreser.setText("");
        jtxtcodigosh.setText("");
        jtxtdnicliente.setText("");
        jtxtfecha_hora.setText("");
        jtxtnombrecliente.setText("");
    }
     void limpiacajasproductos() {
        jtxtidproducto.setText(""); 
        jtxtnombreproduc.setText("");
        jtxtcantidad.setText("");
        jtxtPresio.setText("");
        jtxtmonto.setText("");
     }
     
     void limpiacajastodo (){
         jtxtPresio.setText("");
         jtxtcantidad.setText("");
         jtxtcodigoreser.setText("");
         jtxtcodigosh.setText("");
         jtxtdnicliente.setText("");
         jtxtfecha_hora.setText("");
         jtxtidproducto.setText("");
         jtxtmonto.setText("");
         jtxtnombrecliente.setText("");
         jtxtnombreproduc.setText("");
         jtxttotal.setText("");
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_servicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizarpro;
    private javax.swing.JButton btnagregarrpro;
    private javax.swing.JButton btneliminarrpro;
    private javax.swing.JButton btnmostrarproductos;
    private javax.swing.JButton btnserviciogenerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablaListadoReserva;
    private javax.swing.JTextField jtxtPresio;
    private javax.swing.JButton jtxtactualizarservicio;
    private javax.swing.JTextField jtxtcantidad;
    private javax.swing.JTextField jtxtcodigoreser;
    private javax.swing.JTextField jtxtcodigosh;
    private javax.swing.JTextField jtxtdnicliente;
    private javax.swing.JButton jtxteliminarservicio;
    private javax.swing.JTextField jtxtfecha_hora;
    private javax.swing.JTextField jtxthabitacion;
    private javax.swing.JTextField jtxtidproducto;
    private javax.swing.JTextField jtxtmonto;
    private javax.swing.JTextField jtxtnombrecliente;
    private javax.swing.JTextField jtxtnombreproduc;
    private javax.swing.JTextField jtxttotal;
    private javax.swing.JTable tabledetalle;
    private javax.swing.JTextField txtbuscarxnombre;
    // End of variables declaration//GEN-END:variables
}
